umps [eslint-plugin-jsdoc](https://github.com/gajus/eslint-plugin-jsdoc) from 61.1.9 to 61.1.12.
- [Release notes](https://github.com/gajus/eslint-plugin-jsdoc/releases)
- [Changelog](https://github.com/gajus/eslint-plugin-jsdoc/blob/main/.releaserc)
- [Commits](gajus/eslint-plugin-jsdoc@v61.1.9...v61.1.12)

---
updated-dependencies:
- dependency-name: eslint-plugin-jsdoc
  dependency-version: 61.1.12
  dependency-type: direct:development
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Cookie Xlks <qwerty541zxc@gmail.com>
